keys:
  - &sparkle_host age10anc2xygfedadkvlsc6whyurx7plyquxa47w0c9ut728n8ur4vas677ax7
  - &camellya_host age1kt66h37ezqaryvef402f0665aavu3mpj2l7trdkqctpjl6zeeveswgc50j
  - &sparxie_host age1tddj97txq5mckvzrs8czekp5lc530rc35yw0mtd3w9qxjjwf4vpsn7s8yl

creation_rules:
  - path_regex: hosts/sparkle/secrets\.yaml$
    key_groups:
      - age:
          - *sparkle_host
  - path_regex: hosts/camellya/secrets\.yaml$
    key_groups:
      - age:
          - *camellya_host
  - path_regex: hosts/sparxie/secrets\.yaml$
    key_groups:
      - age:
          - *sparxie_host
