name: Update Flake Inputs

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  update:
    runs-on: native
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update flake inputs
        run: nix flake update

      - name: Check for changes
        id: check
        run: |
          if git diff --quiet flake.lock; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit and push
        if: steps.check.outputs.changed == 'true'
        run: |
          git config user.name "Lapine"
          git config user.email "lapine@lunaire.eu"
          git add flake.lock
          git commit -m "flake: update inputs $(date +%Y-%m-%d)"
          git push
